use futures::{
    future::{self, Ready},
    prelude::*,
};
use std::{
    net::SocketAddr,
    sync::Arc,
};
use tarpc::{
    client, context,
    server::{self, incoming::Incoming, Channel},
    tokio_serde::formats::Bincode,
};

use crate::{dto::InsrtRequest, storage::Storage};
// This is the service definition. It looks a lot like a trait definition.
// It defines one RPC, hello, which takes one arg, name, and returns a String.
#[tarpc::service]
pub trait CachePeer {
    /// Returns a greeting for name.
    async fn query(key: String) -> Option<String>;
    async fn add(key: String, value: String) -> ();
    async fn del(key: String) -> ();
    async fn list(keys: Vec<String>) -> Vec<String>;
    async fn batch(kvs: Vec<InsrtRequest>) -> ();
}

#[derive(Clone)]
pub struct CachePeerServer {
    storage: Arc<Storage>,
    addr: SocketAddr,
}

impl CachePeer for CachePeerServer {
    // Each defined rpc generates two items in the trait, a fn that serves the RPC, and
    // an associated type representing the future output by the fn.
    type QueryFut = Ready<Option<String>>;
    type AddFut = Ready<()>;
    type DelFut = Ready<()>;
    type ListFut = Ready<Vec<String>>;
    type BatchFut = Ready<()>;

    fn query(self, _: context::Context, key: String) -> Self::QueryFut {
        future::ready(self.storage.get_kv(key.as_str()))
    }

    fn add(self, _: tarpc::context::Context, key: String, value: String) -> Self::AddFut {
        self.storage.insert_kv(key.as_str(), value.as_str()).unwrap();
        future::ready(())
    }

    fn del(self, _: tarpc::context::Context, key: String) -> Self::DelFut {
        self.storage.remove_key(key.as_str()).unwrap();
        self.storage.zsets.remove(key.as_str());
        future::ready(())
    }

    fn list(self, _: tarpc::context::Context, keys: Vec<String>) -> Self::ListFut {
        let mut result = Vec::new();
        for key in keys {
            if let Some(value) = self.storage.get_kv(key.as_str()) {
                result.push(value);
            }
        }
        future::ready(result)
    }

    fn batch(self, _: tarpc::context::Context, kvs: Vec<InsrtRequest>) -> Self::BatchFut {
        for kv in kvs {
            self.storage.insert_kv(kv.key.as_str(), kv.value.as_str()).unwrap();
        }
        future::ready(())
    }
}

pub async fn cluster_server(storage: Arc<Storage>) {
    let addr = "0.0.0.0:58080".parse::<SocketAddr>().unwrap();
    let mut listener = tarpc::serde_transport::tcp::listen(addr, Bincode::default)
        .await
        .unwrap();
    listener.config_mut().max_frame_length(usize::MAX);
    listener
        // Ignore accept errors.
        .filter_map(|r| future::ready(r.ok()))
        .map(server::BaseChannel::with_defaults)
        .max_channels_per_key(20, |t| t.transport().peer_addr().unwrap().ip())
        // serve is generated by the service attribute. It takes as input any type implementing
        // the generated World trait.
        .map(|channel| {
            let server = CachePeerServer {
                addr: channel.transport().peer_addr().unwrap(),
                storage: storage.clone(),
            };
            channel.execute(server.serve())
        })
        // Max 10 channels.
        .buffer_unordered(10)
        .for_each(|_| async {})
        .await;
}

pub async fn cluster_client() {
    let addr = "127.0.0.1:58080".parse::<SocketAddr>().unwrap();
    let transport = tarpc::serde_transport::tcp::connect(addr, Bincode::default);
    let client = CachePeerClient::new(client::Config::default(), transport.await.unwrap()).spawn();
}
